quintoandar/hive-metastore-client

docs/requirements.docs.txt, docs/source/getstarted.md, docs/source/index.rst, docs/source/modules.rst
We want to have a nice information design in the [ReadtheDocs page](https://hive-metastore-client.readthedocs.io/en/latest/).
- add getting started menu
- move API specification into one separated section
- refactor index
- fix: add the dependency in requirements.doc.txt (the [build](https://readthedocs.org/projects/hive-metastore-client/builds/12474636/) in RtD was silent failing)
Now we should review and enrich the docs in RtD
=> [DF-289] Update Docs

README.md, docs/source/builders.md, docs/source/getstarted.md, docs/source/index.rst, docs/source/thrift_instructions.md, thrift_files/readme.md
We want to give some clear information about how the project works.
- add doc pages about Thrift and Builders
- update methods information
=> [DF-304] Add docs about Builders and Thrift

README.md, docs/source/index.rst, examples/README.md, examples/add_columns_to_table.py, examples/add_partitions.py, examples/create_database.py, examples/create_table.py, hive_metastore_client/__init__.py, tests/unit/hive_metastore_client/conftest.py, tests/unit/hive_metastore_client/test_hive_mestastore_client.py
We want to let the import path simpler for lib users.
Add HiveMetastoreClient import in init.
Now the users can import with:
```python
from hive_metastore_client import HiveMetastoreClient
```
instead of:
```python
from hive_metastore_client.hive_metastore_client import HiveMetastoreClient
```
With unit-tests + running individual scripts
=> Update client import

.github/workflows/publish.yml, .github/workflows/test.yml
It is better to centralize the docker image to a well supported image, instead of the ones from individual contributors across the web.
Shifting the docker image used by the project actions - flow.
Ran 'test' workflow for the current branch and it ran smoothly.
=> Adjusting docker image path

examples/drop_columns_from_table.py, hive_metastore_client/hive_mestastore_client.py, tests/unit/hive_metastore_client/test_hive_mestastore_client.py
We want to encapsulate logic to drop columns from a table in hive using thrift client classes.
- Added drop_columns_from_table method in HiveMetastoreClient to encapsulate logic of getting table object representation from hive, removing columns from the list of columns and calling alter table to drop the columns.
- Added example on how to use the drop_columns_from_table method.
- Added unit tests.
Running locally and with unit tests.
=> [DF-314] Adding method to drop columns from a table

hive_metastore_client/hive_metastore_client.py, tests/unit/hive_metastore_client/test_hive_metastore_client.py
We don't have an option to create a database only if it doesn't exist in the Metastore Server. So this PR creates the create_database_if_not_exists method, simulating this behavior.
- add method `create_database_if_not_exists` and tests
Unit tests + manual test with server
=> [DF-324] Add create_database_if_not_exists method

docs/source/getstarted.md, hive_metastore_client/hive_metastore_client.py, tests/unit/hive_metastore_client/test_hive_metastore_client.py
We decided that the returning could lead to a misunderstanding of the method, so we'll remove it
- remove returning for method `create_database_if_not_exists`
- Unit tests
_Replace me for what the reviewer will need to pay attention to in the PR or just to cover any concerns after the merge._
=> [DAE-63] Remove method returning for create_database_if_not_exists

docs/source/getstarted.md, examples/add_partitions.py, hive_metastore_client/hive_metastore_client.py, tests/unit/hive_metastore_client/test_hive_metastore_client.py
The server raises an AlreadyExistsException when some partition is added twice.
We want the client doesn't raise an error in this case: if some partition already exists then nothing should be done.
This will make the code cleaner for libs users that don't need to handle errors on their side.
- add a try block for add_partitions_to_table
Unit tests
=> [DAE-63] Handling exception when adding duplicate partitions

docs/source/getstarted.md, examples/create_external_table.py, hive_metastore_client/hive_metastore_client.py, tests/unit/hive_metastore_client/test_hive_metastore_client.py
According to what we discovered in the issue https://github.com/quintoandar/hive-metastore-client/issues/41, there is an error in the Hive metastore server that creates the table as a MANAGED_TABLE instead of EXTERNAL_TABLE when a table is created with default the tableType (None) or equal to EXTERNAL_TABLE.
We decided to enforce the parameter EXTERNAL=TRUE so the table will be created correctly as an external table.
Add new method create_external_table that enforces the parameter EXTERNAL=TRUE and tableType='EXTERNAL_TABLE'
Unit tests + example file.
=> [DAE-92] Add method create_external_table

docs/source/getstarted.md, examples/get_partition_keys.py, examples/get_partition_keys_names.py, examples/get_partition_keys_objects.py, hive_metastore_client/hive_metastore_client.py, tests/unit/hive_metastore_client/test_hive_metastore_client.py
There is no 'SHOW PARTITION' equivalent method in Thrift mapping, therefore we needed to create one to avoid fetching the table/table-schema every single time.
Since both returns (partitions definitions and partition names) could be helpful, we already created both.
- Adding `get_table_partition_keys` and `get_table_partition_keys_names` methods.
- Adding respective examples
- Adding respective unit tests
- Adding new methods to doc
Via unit tests and manual testing;
=> [DAE-94] Add get_table_partition_keys and keys_names methods

CHANGELOG.md, setup.py
Releasing version 1.0.4
- Added create_external_table method - #43 
- Added get_partition_keys_objects and get_partition_keys_names methods - #42
=> [DAE-94] Release 1.0.4

thrift_files/readme.md
The following PR[ #45 ] is changing Thrift source (auto-generated) code. 
We need to keep in mind that any re-build of thrift source code will erase the change, therefore we are adding a list of PRs that need to be re-written/re-deployed in re-build case.
- Adding base message with no linked PR.
=> [DAE-113] Adding base warning about changing thrift base files

thrift_files/libraries/thrift_hive_metastore_client/ThriftHiveMetastore.py, thrift_files/readme.md, thrift_files/source/hive_metastore.thrift
The `max_parts` parameter from `get_partitions` method was limiting our querying to 32k partitions.
Adjusting `max_parts` parameter from `get_partitions` method to handle 64k values.
Executed method get_partitions with the parameter as the new type and it allowed 60k as `max_parts` and returned the expected result.
=> [DAE-113] Changing max_parts from get_partitions method to int32

docs/source/getstarted.md, examples/bulk_drop_partitions.py, hive_metastore_client/hive_metastore_client.py, tests/unit/hive_metastore_client/test_hive_metastore_client.py
We don't have a method to drop all partitions at once. 
So to keep the interface cleaner for the lib's users we decided to add a method that encapsulates the behavior of dropping each partition from a list.
Add method `bulk_drop_partitions`
Unit tests
=> [DAE-116] Add method bulk drop

docs/source/getstarted.md, examples/get_partition_values_from_table.py, hive_metastore_client/hive_metastore_client.py, tests/unit/hive_metastore_client/test_hive_metastore_client.py
Thrift's native `get_partition_values` expect some parameters that we can auto-generate, and also its return contains too much info. We wanted a clear and straight-forward method to get the partition-values from a given table.
The method name looks a bit redundant, being called `get_partition_values_from_table`. However we wanted to leave the base method available... therefore the most clean method name we could think of was this one.
- Adding method `get_partition_values_from_table` method
- Adding example, documentation and unit test to respective method.
- 
Via single and unit test.
=> [DAE-121]  Adding custom get_partition_values method

docs/source/getstarted.md, examples/get_partition_keys.py, examples/get_partition_keys_names.py, examples/get_partition_values_from_table.py, hive_metastore_client/hive_metastore_client.py, tests/unit/hive_metastore_client/test_hive_metastore_client.py
We need a method that returns the partitions names & types.
Adding method `get_partition_keys` that gets the partition keys from a table as a tuple: (name, type).
Unit tests + testing with Hive metastore server.
=> [DAE-117] Add method to get partitions with name and type

hive_metastore_client/hive_metastore_client.py, tests/unit/hive_metastore_client/test_hive_metastore_client.py
When using the method `get_partition_values_from_table` with non-partitioned tables we get an exception:
```python
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
```
We decided to handle this as an empty return, once the table does not have partitions.
modify method `get_partition_values_from_table` handle to handle the Exception
Unit + testing with Hive Metastore Server
_Replace me for what the reviewer will need to pay attention to in the PR or just to cover any concerns after the merge._
=> [DAE-126] Handle exception when table has no partitions

hive_metastore_client/hive_metastore_client.py, tests/unit/hive_metastore_client/test_hive_metastore_client.py
When running an ALTER TABLE Hive stores the types of columns from table schema in sequential order to enforce the same types after the ALTER TABLE. However when performing our abstraction of DROP COLUMN, the types may change, since the schema will definitely change.
Currently, if we try to drop a column that changes this 'types order', the following error returns:
> thrift_files.libraries.thrift_hive_metastore_client.ttypes.InvalidOperationException: InvalidOperationException(message='The following columns have types incompatible with the existing columns in their respective positions :\ncolumn_name')
- Adding a call to change metastore settings while in `drop_columns_from_table`:
Allowing, in the current execution, the changing of types when comparing the table schema prior and after …
=> [DAE-133] Removing types-comparison when dropping a column

CHANGELOG.md, setup.py
Release version 1.0.7
* Added method `add_partitions_to_table` to add partitions receiving an exception if some partition already exists 
([#57](https://github.com/quintoandar/hive-metastore-client/pull/57))
* Removed types-comparison when dropping a column ([#56](https://github.com/quintoandar/hive-metastore-client/pull/56))
* Handled the partitions adding inside a loop (adding each partition individually) to fix a silent bug (if some 
partition already existed, none of the list were added) ([#57](https://github.com/quintoandar/hive-metastore-client/pull/57))
=> [DAE-144] Release 1.0.7

hive_metastore_client/builders/serde_info_builder.py, hive_metastore_client/builders/table_builder.py
We've been using the hive-metastore listener to track all DDLs running on the server that generates a payload sent to the Kafka topic in order for the Apache Atlas can read them and create the objects in your ecosystem.
Using the lib we faced a problem with the creation of tables based on Json schema, actually, the creation of the table worked as expected, but the listener could not get the json schema, given the following error:
```
2021-08-06T18:26:43,438 ERROR [pool-8-thread-2] metadata.Table: Unable to get field from serde: org.apache.hive.hcatalog.data.JsonSerDe
java.lang.NullPointerException: null
```
In the first shot, that error looks like something related to the listener code, but after realizing plenty of tests with many kinds of changes in the listener, I could not find any …
=> [DAE-145] Change the default values for create table event

CHANGELOG.md, setup.py
Release version 1.0.8
* Added if clause to check the default values for TableBuilder and SerdeInfoBuilder constructor
([#62](https://github.com/quintoandar/hive-metastore-client/pull/62))
=> [DAE-145] Release 1.0.8

hive_metastore_client/hive_metastore_client.py, tests/unit/hive_metastore_client/test_hive_metastore_client.py
Code on `get_partition_values_from_table` was catch a too general exception unnecessarily.
It also caused exceptions on the Hive Metastore.
Replaces a try-catch statement to an if.
- Unit tests running
- Stage test environment:
- Returning same correct partition values for parquet partitioned tables
- Returning same correct partition values for json partitioned tables
- Returning same results (empty list) for json unpartitioned tables
- Not raising exceptions on HMS
=> Remove exception when getting partition values

CHANGELOG.md, setup.py
Release 1.0.9
* Stop inducing exception on Hive Metastore server when trying to retrieve partition values with `get_partition_values_from_table` for partitionless tables.
([#64](https://github.com/quintoandar/hive-metastore-client/pull/64))
=> Release 1.0.9

.github/workflows/publish.yml, .github/workflows/test.yml, examples/add_partitions_if_not_exists.py, examples/add_partitions_to_table.py, hive_metastore_client/hive_metastore_client.py, requirements.lint.txt, tests/unit/hive_metastore_client/test_hive_metastore_client.py
The runner used for executing the Github Actions appears to be outdated and not working.
The step will be stuck finding for a runner:
- updating the runner to `ubuntu-22.04`
- updating black due to dependencies issue
Running PR workflows
=> Update Workflow runner

docs/requirements.docs.txt, docs/source/hive_metastore_client.builders.rst, docs/source/hive_metastore_client.rst
The docs on Read the Docs site are not being built.
Bump local Sphinx to the version used in ReadTheDocs.
update some docs to test building
Locally
_Replace me for what the reviewer will need to pay attention to in the PR or just to cover any concerns after the merge._
=> Bump Sphinx version
